on: push
name: Run Go Tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      env:
        GO111MODULE: "on"
    - name: run
      uses: cedrickring/golang-action@1.4.1
      with:
        args: go test -v .